<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class Todo extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray( $request )
    {

        return [
            "user" => $request->user( ),
            "userId" => $this->user_id,
            "id" => $this->id,
            "title" => $this->title,
            "description" => $this->description,
            "completed" => $this->completed == 1 ? true: false
        ];
    }

    public function with($request)
    {
        return is_array( $this->data ) ? $this->data:[]; // TODO: Change the autogenerated stub
    }
}
